export const urls = {
    ETH:{
        mainnet:"https://mainnet.infura.io/v3/",
        testnet:"https://goerli.infura.io/v3/"
    },
    KLAY:{
        mainnet:"https://public-node-api.klaytnapi.com/v1/cypress",
        testnet:"https://api.baobab.klaytn.net:8651"
    },
    POLY:{
        mainnet:"https://polygon-mainnet.infura.io/v3/",
        testnet:"https://polygon-mumbai.infura.io/v3/"
    },
    TRON:{
        mainnet:"",
        testnet:""
    },
    BSC:{
        mainnet:"https://bsc-dataseed1.binance.org/",
        testnet:"https://data-seed-prebsc-1-s1.binance.org:8545/"
    }
}